# Universal Locomotion Hyperparameters
common:
  device: "cuda"
  total_timesteps: 1000000

environments:
  humanoid:
    id: "Humanoid-v5"
    learning_rate: 3.0e-4
    batch_size: 128
  ant:
    id: "Ant-v5"
    learning_rate: 2.5e-4
    batch_size: 64
  cheetah:
    id: "HalfCheetah-v5"
    learning_rate: 3.0e-4
    batch_size: 256
